# -*- python -*-

import os
opts = Options ()
opts.Add (BoolOption ('debug', 'Set to 1 to build with debugging symbols', 0))
opts.Add (BoolOption ('profile', 'Set to 1 to build with profiling support', 0))

env = Environment (options = opts,
                   CCFLAGS = '-pedantic -Wall -Wno-unknown-pragmas',
                   LINKFLAGS = '-mwindows',
                   PLATFORM = 'cygwin',
                   CPPPATH = ['d:/usr/local/include'],
                   ENV = os.environ,
                   CPPDEFINES = {'_WIN32_WINNT': 0x0501,
                                 '_WIN32_IE': 0x0000,
                                 'WIN32_LEAN_AND_MEAN': 1,
                                 'DEBUG': '${int (debug)}',},
                   LIBS = [],
                   LIBPATH = [],
                   )

build_with_debug = ARGUMENTS.get ('debug', 0)
build_with_profile = ARGUMENTS.get ('profile', 0)
gcc_strict = ARGUMENTS.get ('strict', 0)

if int (build_with_debug):
    env.Replace (CCFLAGS = env['CCFLAGS'] + ' -g')
    env.Replace (LINKFLAGS = env['LINKFLAGS'] + ' -g')

if int (build_with_profile):
    env.Replace (CCFLAGS = env['CCFLAGS'] + ' -pg')
    env.Replace (LINKFLAGS = env['LINKFLAGS'] + ' -pg')
    env.Replace (LIBS = env['LIBS'] + ['gmon'])

if int (gcc_strict):
    env.Replace (CCFLAGS = env['CCFLAGS'] + ' -Werror')

if not (int (build_with_debug) or int (build_with_profile)):
    env.Replace (CCFLAGS = env['CCFLAGS'] + ' -O3')

env.Program ('siaynoq',
             ['main.c', 'siaynoq.c', 'drawing.c', 'notif_area.c', 'hotkeys.c', 'tiling.c', 'tools.c'],
             LIBS = env['LIBS'] + ['wtsapi32', 'shell32', 'gdi32', 'ole32'])
env.SharedLibrary ('wafer',
                   ['hooks.c', 'tools.c'],
                   CCFLAGS = env['CCFLAGS'] + ' -DEXPORT_DLL')
